Fixing QT
epfl-scitas/spack-packagelist pull request #112
Opened 2018-10-31 05:31 UTC by nvarini

2018-10-31 14:08 UTC, rmsds requested changes
Besides my comment, we also need to verify all the not yet installed dependencies are added to the blacklist. From `spack spec -I qt@5.10.0 +opengl+webkit ^python@3.6.5+optimizations+tk %gcc@7.3.0 target=x86_E5v4_Mellanox`, I see:
```
glib
libmng
lcms
libtiff
mesa
expat
libbsd
glproto
libxdamage
damageproto
fixesproto
libxfixes
libxext
libxshmfence
libxv
videoproto
libxvmc
presentproto
py-mako
py-markupsafe
```

2018-10-31 14:08 UTC, rmsds commented on paien.yaml
> +      - qt@5.10.0 +opengl+webkit ^mesa
Do we need the `^mesa`, it seems to concretize just fine without it.

Also, as (at least) `glib` and `mesa` depend on Python we need to add an explicit dependency to one of our sanctioned Python installations, maybe:
```suggestion
      - qt@5.10.0 +opengl+webkit ^python@3.6.5+optimizations+tk
```

2018-11-02 07:31 UTC, rmsds approved these changes
Looks good to me.

And I'll wait for another review before merging because I don't know the use cases very well.
Pinging @alalazo and @nrichart

2018-11-06 12:19 UTC, alalazo approved these changes
Reminder to myself: in the next release we should probably blacklist implicits by default.

2018-11-06 12:19 UTC, merged

2018-11-06 12:19 UTC, alalazo commented
Thanks @nvarini !