Added scorep
epfl-scitas/spack-packagelist pull request #117
Opened 2018-11-08 12:22 UTC by nvarini

2018-11-08 14:16 UTC, rmsds submitted a review, later dismissed

2018-11-08 14:16 UTC, rmsds commented on paien.yaml
>  # TODO: update scorep as described in issue SL-557
Could you also delete this comment? I think your commit addresses the issue in question.

2018-11-19 07:54 UTC, alalazo requested changes
Looking at Jenkins CI, it seems that `pdt-toolkit` fails to build (and `scorep` is then installed accidentally without it). Can you fix this? Also: can you make sure we are using the same Qt 5.10.0 that is installed on the clusters?

2018-11-29 13:29 UTC, alalazo requested changes
Almost there. It seems installation is now failing only for `gcc@7.3.0`:
```console
...
==> Installing scorep
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
1 out of 1 hunk ignored -- saving rejects to file src/adapters/compiler/gcc-plugin/scorep_plugin_inst_descriptor.inc.c.rej
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
1 out of 1 hunk ignored -- saving rejects to file src/adapters/compiler/gcc-plugin/scorep_plugin_tree-flow.h.rej
==> Using cached archive: /home/scitasbuild/paien/pr/spack.DGgpu/var/spack/cache/scorep/scorep-4.1.tar.gz
==> Staging archive: /home/scitasbuild/paien/pr/spack.DGgpu/var/spack/stage/scorep-4.1-uy2canzhl34vr4xzrmjt63zc5vadywqi/scorep-4.1.tar.gz
==> Created stage in /home/scitasbuild/paien/pr/spack.DGgpu/var/spack/stage/scorep-4.1-uy2canzhl34vr4xzrmjt63zc5vadywqi
==> Patch gcc7.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/home/scitasbuild/paien/pr/spack.DGgpu/var/spack/repos/builtin/packages/scorep/gcc7.patch' '-d' '.'
...
```
because of a patch that couldn't / shouldn't be applied?

2018-12-03 08:38 UTC, alalazo commented
Just checked the result of Jenkins, and I couldn't see any error. Every architecture installs 5 versions of `scorep`, which is what we want. Trying to merge it and see how it deploys.

2018-12-03 08:38 UTC, alalazo approved these changes

2018-12-03 08:38 UTC, merged