Blacklist fixes: py-pysam and py-macs
epfl-scitas/spack-packagelist pull request #122
Opened 2018-11-15 09:07 UTC by rmsds

* following #83
* py-py-sam is really py-pysam
* py-macs had been un-blacklisted by #104, the idea was to have it pop up when people search for macs, even though it's activated it's mostly a standalone cli utility

2018-11-15 09:19 UTC, nrichart reviewed
Py-macs was installed only for one version of python?
Should we add a suffix on python modules -py2 -py3

2018-11-27 14:06 UTC, rmsds commented
Thanks for the review @nrichart.

> Py-macs was installed only for one version of python?
Yes, it's only python 2.6-2.7 compatible.

> Should we add a suffix on python modules -py2 -py3
Technically I don't think we need it as the shebang usually points to the correct python.

I've also considered testing/proposing autoloading of python whenever anything depends on it (I saw it [here](https://spack.readthedocs.io/en/latest/tutorial_modules.html#autoload-dependencies)). It should  avoid most issues when mixing up python modules.

2019-02-13 12:25 UTC, alalazo requested changes

2019-02-13 12:25 UTC, alalazo commented on configuration/modules.yaml
> -      'py-macs',
Let's leave `py-macs` blacklisted for now

2019-02-13 13:05 UTC, alalazo approved these changes

2019-02-13 15:31 UTC, merged