Changed gurobi from external to core
epfl-scitas/spack-packagelist pull request #165
Opened 2019-11-01 08:56 UTC by batatasfritas

2019-11-04 10:17 UTC, rmsds requested changes
Looks good, just needs the obsolete lines from `packages.yaml` to be deleted.

2019-11-04 10:17 UTC, rmsds commented on configuration/packages.yaml
> +  #     gurobi@8.1.1%gcc@4.8.5: /ssoft/spack/external/gurobi/8.1.1
I think we should actually remove these lines.

2020-11-09 10:42 UTC, nrichart commented
@rmsds this also should be merge for https://github.com/epfl-scitas/spack/pull/254

2020-11-12 16:47 UTC, rmsds approved these changes, later dismissed

2020-11-20 15:10 UTC, nrichart approved these changes
lgtm

2020-11-20 15:11 UTC, merged