Package hisat2
epfl-scitas/spack-packagelist pull request #18
Opened 2017-10-17 10:56 UTC by matteoguglielmi

2017-10-23 07:18 UTC, alalazo requested changes
We need to check the version of python required. If that doesn't matter, we should move this into Core?

2017-10-23 07:18 UTC, alalazo commented on packages.yaml
> +      - hisat2@2.1.0
I see this in `hisat2` package:
```python
files = glob.iglob('*.py')
for file in files:
    if os.path.isfile(file):
        install(file, prefix.bin)
```
Did anybody check if the version of the python interpreter matters for these scripts, or if they are portable from 2.7.5 (system python) to 3.6.1 ?

2017-11-01 09:14 UTC, rezzonico commented on packages.yaml
> +      - hisat2@2.1.0
Not portable to python 3

2017-11-01 14:09 UTC, alalazo approved these changes

2017-11-01 14:11 UTC, merged