Reactivating fenics
epfl-scitas/spack-packagelist pull request #183
Opened 2020-07-20 11:45 UTC by nrichart

depends on https://github.com/epfl-scitas/spack/pull/253

2020-07-23 12:07 UTC, rmsds requested changes
And I think we also need to add `fenics` to the whitelist in the `modules.yaml`.
(Or maybe we don't need it as it is explicit?)

2020-07-23 12:07 UTC, rmsds commented on humagne.yaml
>    mpi-lapack-applications:
Should fenics just be once under here? Instead of on the gnu/intel-specific sections?
Both specs look identical.

2020-07-24 09:17 UTC, nrichart commented
It should be fine for the module it should not be in a part that is blacklisted

2020-07-24 10:24 UTC, rmsds approved these changes
LGTM

2020-07-27 07:03 UTC, merged