Packages.yaml modified to accept tensorflow as external package
epfl-scitas/spack-packagelist pull request #2
Opened 2017-02-22 11:00 UTC by nvarini

2017-03-02 15:47 UTC, alalazo requested changes
You added the lines to the wrong `packages.yaml`. The one you want to modify is in the `configuration` folder. Can you please update the PR?

2017-03-03 09:06 UTC, alalazo commented on configuration/packages.yaml
> +      tensorflow@0.10.0rc0+cuda@7.5.18+cudnn@4.0.cuda7%gcc@5.3.0: /ssoft/spack/external/tensorflow/0.10.0rc0/tensorflow_venv_gpu
Did you try the external package before committing? I think you want either to say:
```
tensorflow@0.10.0rc0 ^cuda@7.5.18 ^cudnn@4.0.cuda7%gcc@5.3.0: /ssoft/spack/external/tensorflow/0.10.0rc0/tensorflow_venv_gpu
```
or more likely:
```
tensorflow@0.10.0rc0+cuda%gcc@5.3.0: /ssoft/spack/external/tensorflow/0.10.0rc0/tensorflow_venv_gpu
```
When you ask **for variants** you don't need to have **versions** for them.

2017-03-03 11:15 UTC, nvarini commented on configuration/packages.yaml
> +      tensorflow@0.10.0rc0+cuda@7.5.18+cudnn@4.0.cuda7%gcc@5.3.0: /ssoft/spack/external/tensorflow/0.10.0rc0/tensorflow_venv_gpu
Well, this version of tensorflow has been compiled with gcc4.9.3 cuda7.5.18 cudnn4.0.cuda7. If you don't have this constraint it does not work

2017-03-03 11:49 UTC, alalazo commented on configuration/packages.yaml
> +      tensorflow@0.10.0rc0+cuda@7.5.18+cudnn@4.0.cuda7%gcc@5.3.0: /ssoft/spack/external/tensorflow/0.10.0rc0/tensorflow_venv_gpu
What I mean is that you have a syntax error above.

2017-03-22 14:58 UTC, alalazo approved these changes

2017-03-22 15:01 UTC, merged

2017-03-22 15:01 UTC, alalazo commented
These changes are fine: I'll merge them. We also need an entry in the upper `packages.yaml` to tell Jenkins where do we want this to be installed. And maybe something in `modules.yaml` if we need custom content in the module file.